spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev
    username: dev
    password: pwdev
  jpa:
    hibernate:
      ddl-auto: validate
      hbm2ddl:
        delimiter: ";"
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: recipe_db_schema.sql